name: Azure CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: '15.x'
      - name: Install dependencies
        run: npm install
        working-directory: leap/
      - name: Build Leap
        run: npm run build
        working-directory: leap/
      - name: Generate docs
        uses: nikeee/docfx-action@v1.0.0
        with:
          args: docfx.json
        env:
          DOCFX_SOURCE_BRANCH_NAME: ${{env.GITHUB_REF}}
      - name: Build and deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_LIVELY_BUSH_04849FE03 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: upload
          skip_app_build: true
          app_location: /_site # Action expects pre-built app here when skipping build (see https://github.com/Azure/static-web-apps/issues/248#issuecomment-790723641)

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close pull request
    steps:
      - name: Close pull request
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_LIVELY_BUSH_04849FE03 }}
          action: close
